{% set version = "0.11.1" %}

package:
  name: trio-websocket
  version: {{ version }}

source:
    url: https://github.com/HyperionGray/trio-websocket/archive/refs/tags/{{ version }}.tar.gz
    sha256: 31b33561be82ea8f748ca2d8adaf3c45a2003c1a5e1550d7cf44e5a884564bce

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python
    - trio >=0.11
    - wsproto >=0.14
    - exceptiongroup # [py<311]

test:
  source_files:
    - pytest.ini
    - tests
  imports:
    - trio_websocket
  commands:
    - pip check
    - pytest -vv  # [not arm64]
    ## Skipped tests on osx-arm64 due to our CI limitations with networking libraries
  requires:
    - attrs >=19.2.0
    - pip
    - pytest >=4.6
    - trustme
    - pytest-trio >=0.5.0

about:
  home: https://github.com/HyperionGray/trio-websocket
  summary: WebSocket library for Trio
  license: MIT
  description: |
    trio-websocket is a WebSocket library for Trio. It is a port of the
    wsproto library to Trio, and is designed to be used with the Trio async
    I/O library.
  # TODO: revisit if/after merge of https://github.com/HyperionGray/trio-websocket/pull/168
  license_file: LICENSE
  license_family: MIT
  doc_url: https://trio-websocket.readthedocs.io
  dev_url: https://github.com/HyperionGray/trio-websocket

extra:
  recipe-maintainers:
    - bollwyvl
